# Generated by Django 6.0.8 on 2026-09-30 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbrales_dias_json', models.CharField(default='[30, 15, 7]', max_length=100)),
                ('umbral_km', models.IntegerField(default=1000)),
                ('correo_notificaciones', models.EmailField(default='alertas@alvolante.com', max_length=254)),
            ],
            options={
                'db_table': 'flota_configuracion',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'flota_usuario',
            },
        ),
        migrations.CreateModel(
            name='VehiculoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('Automóvil', 'AUTOMOVIL'), ('Motocicleta', 'MOTOCICLETA'), ('Otro', 'OTRO')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('kilometraje_actual', models.IntegerField(default=0)),
                ('vencimiento_soat', models.DateField(blank=True, null=True)),
                ('vencimiento_tecnomecanica', models.DateField(blank=True, null=True)),
                ('fecha_ultima_lectura', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='flota.usuariomodel')),
            ],
            options={
                'db_table': 'flota_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='MantenimientoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('criterio', models.CharField(choices=[('fecha', 'FECHA'), ('kilometraje', 'KILOMETRAJE')], max_length=50)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('kilometraje_objetivo', models.IntegerField(blank=True, null=True)),
                ('cumplido', models.BooleanField(default=False)),
                ('fecha_cumplimiento', models.DateField(blank=True, null=True)),
                ('kilometraje_cumplimiento', models.IntegerField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='flota.vehiculomodel')),
            ],
            options={
                'db_table': 'flota_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='LecturaKilometrajeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.IntegerField()),
                ('fecha_lectura', models.DateField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='flota.vehiculomodel')),
            ],
            options={
                'db_table': 'flota_lectura_kilometraje',
            },
        ),
    ]
