# Generated by Django 6.0.8 on 2026-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
